version: 2
formats: []

build:
  os: ubuntu-22.04
  tools:
    python: '3.10'
  jobs:
    # https://github.com/readthedocs/readthedocs.org/issues/4912
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
    post_install:
      - poetry export --no-interaction -f requirements.txt --output requirements.txt --with docs
      - pip install -r requirements.txt

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: html