version: 2
formats: []

build:
  os: ubuntu-20.04
  tools:
    python: '3.10'

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: html

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs